### ISSUE TITLE
Bot shouldn't respond to consecutive r-signals from same cmdr.

### ISSUE THREAD

**Issue by Belserium** [FuelRats/pipsqueak#102]
The bot should not respond to consecutive r-signals from same irc-nick/commander within the same "session" or to accept more cases is the signalling commander already has an open case. A cool-off timer could work too.

**Comment by Marenthyu** [comment]
It currently doesnt open new cases when the same nick r-signals. It only does the 'got rsig from clien are you on o2' messages. I can remove those if an active rescue for the same nick exists, expect a commit for this tonight in -newirc, will ship with that branch.
