### ISSUE TITLE
!xb and !pc inconsistent with !sys

### ISSUE THREAD

**Issue by SimplyLinn** [FuelRats/pipsqueak#105]
With !sys, the person issuing the command gets highlighted by the bot, but with both the !pc and !xb command, the bot just spits out that the case has been changed, without highlight.

!cr also omits the highlight, but since the message from the bot there is more directed to all rats that are on/thinking about participating in the case rather than to confirm to the dispatch that the command succeeded, its good.

**Comment by Marenthyu** [comment]
Closed by #106
