### ISSUE TITLE
Integrate !assigned command

### ISSUE THREAD

**Issue by kenneaal** [FuelRats/pipsqueak#123]
List active cases with their assigned rats:

<MechaSqueak> Assigned Rats: [1]: CMDR Test: Absolver, Xlexious [2] CMDR TestTwo: Marenthyu, NoLifeKing [3] CMDR AnotherTest: {NONE}

**Comment by Marenthyu** [comment]
Might get very long. May look into with a new parameter like -r for rats

**Comment by Marenthyu** [comment]
Implemented in !list -r
