### ISSUE TITLE
Alter-egos

### ISSUE THREAD

**Issue by stehx26** [FuelRats/pipsqueak#124]
I have 3 accounts I might perform rescues on:
1. Esxste - XBOX
2. Esxste - PC
3. Azured - XBOX

I need to be able to change my nick to Azured in order to perform rescues with that account, and help dispatchers with !go/!assign commands, and not confuse clients

I want all rescues to be logged against 1 account - my existing  esxste account.

**Comment by Marenthyu** [comment]
will make it so the assign tries to match your username when choosing the rat in your account.
