### ISSUE TITLE
Deletions

### ISSUE THREAD

**Issue by stehx26** [FuelRats/pipsqueak#129]
To ensure accurate data collection and case statistics; 

A form to request deletions would be good; so dispatchers can log cases to be deleted or a  function similar to !clear; like !md (Mark for Deletion) that closes the case and marks it for review and deletion.

**Comment by SuperManifolds** [comment]
The paperwork problem report form http://goo.gl/forms/d34igY1ED9 already has an option for reporting a rescue for deletion.

However I think the idea of a mark for deletion command is a good one

**Comment by Marenthyu** [comment]
I should be able to do that. !mdlist to list rescues marked for deletions, it will list client and system like !closed does, !quoteid <fullid> to quote any case from the database (will always poll the api so use it sparingly) to get more information if nessesary and of course !md/!mdadd to add a new rescue that is currently also on the board for deletion. Might also add !mdaddid/!mdidadd/!mdid <fullid> to allow to mark any rescue from the database to be marked for deletion so people can approve it. And finally, a !mdremove/!mdr/!mddeny to remove a case from the marked list.

**Comment by Belserium** [comment]
Should a reason text be mandatory with it? Would help when a rat gets triggerhappy with the delete pistol.

**Comment by Marenthyu** [comment]
I am happy to implement it, though the way I implement it may have to change depending on how @xlexi implements the data field search functionality.

**Comment by stehx26** [comment]
This might be pushing further, but could the bot list the cases awaiting deletion in !list to deletion enabled users? i.e !list case 1, case 2; 1 Inactive Case; 1 Case marked for deletion

**Comment by Marenthyu** [comment]
Because of the way I am implementing this (and because we do not want to touch the data model), this would not be recommended. I am adding a separate command to list marked rescues which will poll the API in a specific way every time it is called to ensure it is up-to-date, but this could get very taxing if it is done every time !list gets called (which is pretty often).

**Comment by stehx26** [comment]
Fair enough :D

**Comment by kenneaal** [comment]
Also, the adage that you don't need one command to do everything. Although loosely related, the functionality of deleting cases isn't really directly part of the main board list. Maybe !delete without an argument lists delete marked cases?

**Comment by Marenthyu** [comment]
On that regard, which permission level should be used for the removal of the mark-for-deletion? I am suggesting dispatch and above (dispatch is not yet implemented, so effectively overseer and above) for obvious reasons or rat and above as it does not entail actually deleting the rescue, but rather just removes the appeal for deletion and closes the case for good.

**Comment by Marenthyu** [comment]
@kenneaal That should be possible, but would prohibit rats from using the command, which, again, would be okay in my opinion, but could be allowed - depending on what the ops team thinks.
