### ISSUE TITLE
Twitter functionality

### ISSUE THREAD

**Issue by eddedmondson** [FuelRats/pipsqueak#130]
Feature request: I'm happy to transfer over the Twitter bot's functionality. The Perl code for it is simple, and is at https://github.com/eddedmondson/tweetsqueak

Given a suitable Python module it should be pretty easy to implement the !tweet command, and the flimsy security can probably be replaced by more up to date API checks? Keeping the rate limit would be nice, but not too important if the security is better.

For API keys and to kill the current bot, email eddedmondson@gmail.com when it's ready to go live.

**Comment by Marenthyu** [comment]
as far as i know tweeting is as simple as doing a http request to a specific twitter endpoint, so it should be easy pz. I'll mail you for the api key and will implement it in the next few days, but i need a day off right now.

**Comment by eddedmondson** [comment]
Incidentally, RatMama is kicking TweetSqueak for being repetitive. Hopefully this will be resolved with a functionality merge :)

**Comment by SuperManifolds** [comment]
That could also be resolved if you just registered the thing so I could grant it immunity

**Comment by eddedmondson** [comment]
Outstanding question I meant to ask when I had time - do I register it as a commander? Also, since I wasn't expecting it I wasn't going to bother when it would be retired relatively soon.

**Comment by SuperManifolds** [comment]
just use /ns register, highlight me and I will manually approve it

**Comment by eddedmondson** [comment]
I'll have to configure an actual client to do that, which I might do after the current rescue I'm on!
