### ISSUE TITLE
!sys bug

### ISSUE THREAD

**Issue by stehx26** [FuelRats/pipsqueak#137]
Doesn't overwrite original system location in paperwork

Note from Kilo363
found a PW issue, don't know if it's known or not. Last rescue the system was corrected during the rescue, and bot updated by dispatch. When generting sys name in pw it still showed the original name given in the r@ts1gn@l

**Comment by Marenthyu** [comment]
Can't reproduce.

**Comment by Marenthyu** [comment]
couldnt reproduce with kilo, closing as unreproducable for now.
