### ISSUE TITLE
Bug !prep !pcwing 

### ISSUE THREAD

**Issue by stehx26** [FuelRats/pipsqueak#145]
<&Ratmama[BOT]> Rat Mama has all the cheese! Incoming Client: xNightflash - System: Sol 285 Sector SV-Y a16-2 - Platform: PC - O2: OK - Language: German (de)
09:04:22 M<%MechaSqueak[BOT]> Sopel: http://sopel.chat RATSIGNAL - CMDR xNightflash - System: Sol 285 Sector SV-Y a16-2 - Platform: PC - O2: OK - Language: German (de) (Case #5)
09:04:25 ← kilo[bootcamp](was kilosleep) left  
09:04:36 M<%MechaSqueak[BOT]> Sopel: http://sopel.chat KeyError: Identifier('kilo[bootcamp]') (file "/home/mecha/drillsqueak-websocket/pipsqueak/lib/python3.4/site-packages/sopel/tools/target.py", line 65, in clear_user)
09:04:57 C<+Clapton[PC]> Clapton 5j
09:05:08 T<+The_Armed_501st> Andrew Liddell Client still isn't in here
09:05:10 N<+Nerixel[PC-AU]> Nerixel 11j
09:05:19 T<+The_Armed_501st> Andrew Liddell Go Clapton[PC]
09:05:44 C<+Clapton[PC]> Clapton omw
09:05:59 T<+The_Armed_501st> Andrew Liddell !assign 5 Clapton[PC]
09:05:59 M<%MechaSqueak[BOT]> Sopel: http://sopel.chat xNightflash: Please add the following rat(s) to your friends list: Clapton
09:06:08 T<+The_Armed_501st> Andrew Liddell !prep 5
09:06:08 M<%MechaSqueak[BOT]> Sopel: http://sopel.chat 5: Please drop from super cruise, come to a complete stop and disable all modules EXCEPT life support
09:06:13 T<+The_Armed_501st> Andrew Liddell !pcfr 5
09:06:14 M<%MechaSqueak[BOT]> Sopel: http://sopel.chat 5: To send a friend request, go to the menu (Hit ESC), click friends and private groups, and click ADD FRIEND

**Comment by stehx26** [comment]
Strike this... morning fuzzyness

Thought it was a bug, but its not. Just the way !facts work

**Comment by Marenthyu** [comment]
your copypasting with the realnames behind the names kinda confused me, lol. but yea, it is working as intended.
