### ISSUE TITLE
List not assigned rescues

### ISSUE THREAD

**Issue by SuperManifolds** [FuelRats/pipsqueak#146]
> !list -na ("not assigned" or something like that)
> It shows only the active cases with NO rats assigned to it, it will make easier to dispatch and rats when there is a lot of cases on going.    

Suggested on the reddit feedback thread by by [Mila Strelok](https://www.reddit.com/r/FuelRatDiscussion/comments/4yhiqo/irc_bot_and_process_feedback/d6xxj40)    

I think it is a very good suggestion

**Comment by SuperManifolds** [comment]
Posting this for @Marenthyu as he is on unstable internet and can't reply himself   

> "Will work on it on the next train, should be easy enough. As the Parameter has to be a single character, i will use -u. For now use -r - it lists all assigned rats on !list."

**Comment by Marenthyu** [comment]
already done on my drive, just need to push it. Will do so tomorrow.
