### ISSUE TITLE
Implement comma injection in Mechasqueak

### ISSUE THREAD

**Issue by kenneaal** [FuelRats/pipsqueak#152]
We need to look into a feasible way of injecting a , into the Mechasqueak Paperwork link between the commander name being assigned to do paperwork and the "Do the paperwork" statement.

Points to consider.
- , is ASCII 42. U+002C UTF8. More feasible in UTF? Perhaps EBDIC is needed.
- The comma must be smart injected based on whether there is a commander assigned to first limpet in the !close command.
- Edge case: When a commander is mentioned in the !close, the case of D in "Do" should be lowercased.

**Comment by Marenthyu** [comment]
ouch, i didnt think about 3 -That will be hard. Otherwise, 1 and 2 are done by bdf37ad
