### ISSUE TITLE
[suggestion] suggestion for a new command

### ISSUE THREAD

**Issue by fixiehearts** [FuelRats/pipsqueak#172]
I'm not sure if this thread is on the right place, help me out if I'm wrong.

short question: is it possible to have a command that shows you all rats assigned for a specific case?
something like: !quote # -r

I know I can do !list -r or !quote # but it will result in lots of information showing up either in #fuelrats or #ratchat. Sometimes it can get really busy and one tend to forget which rats, which client and how they relate.

fixiehearts

**Comment by Marenthyu** [comment]
This is the right place for it. :)

I dont see why this would be needed because of the aforementioned. You can simply use the commands in a PM and it wont spam anything.

Feel free to correct me though, but otherwise i will close this issue.
