### ISSUE TITLE
Add details for contributing

### ISSUE THREAD

**Issue by trezy** [FuelRats/pipsqueak#3]
Github will [automatically link to a CONTRIBUTING.md file](https://github.com/blog/1184-contributing-guidelines) if one is present in your repo. @duk3luk3, I'd love to see one detailing the requirements you have for working on pipsqueak. It should include the forking requirement, any code style standards, PR requirements, and anything else necessary for a PR to be accepted.

Check out [puppet's CONTIRIBUTING.md](https://github.com/puppetlabs/puppet/blob/master/CONTRIBUTING.md) for a great example.

**Comment by duk3luk3** [comment]
What do you think about this?

**Comment by trezy** [comment]
:+1: :party:
