### ISSUE TITLE
Define the running environment

### ISSUE THREAD

**Issue by trezy** [FuelRats/pipsqueak#32]
I'd like to see either:
1. A list of requirements for the ideal pipsqueak environment, or
2. A Vagrantfile/Ansible playbook that sets up such an environment.

I'm gonna be pushing for this on all of our repos so that anybody can pull down the code, run `vagrant up`, and have a functioning project.

I'll be doing this with the API repo shortly so the work for this ticket can be based on that. I can also do the legwork for this ticket, I'd just need number 1. :-)

**Comment by tyrope** [comment]
The answer to your question is answered in the [README](https://github.com/FuelRats/pipsqueak/blob/sopel-master/README.md), is it not? If not, what exactly do you wish to know?

**Comment by trezy** [comment]
What I'm looking for is the actual production environment that's being used. Is it running on Windows? Linux? What distro? What version of Python? What is installed, if anything, other than Sopel?

**Comment by duk3luk3** [comment]
Python 3 with all the packages listed in requirements.txt.

Ther production environment right now is a debian wheezy VM with a handcompiled python 3.4 and virtualenv. It's not much of a production environment.

**Comment by tyrope** [comment]
Py2.7.4 on Windows.

**Comment by rwaltr** [comment]
I use Korora, with virtualenv and python3. but that is  a test envioment

**Comment by duk3luk3** [comment]
The production environment **should** be: Something with a working python3.4+, which also implies a working virtualenv script.

Nothing else is needed.

**Comment by duk3luk3** [comment]
Someone should make that vagrant file though.

**Comment by trezy** [comment]
I'll work on one once I get that stupid Elasticsearch issue figured out.

**Comment by Blackphidora** [comment]
Vagrant my rear end.... ;)

**Comment by trezy** [comment]
I've got an ansible playbook ready to go for setting up mecha2 on a digital ocean server. The only issue I'm running into is that when loading the repo from scratch and following the instructions in the README the ratboard doesn't seem to work right but it mecha doesn't want to respond to ratboard commands. I'm having trouble figuring out why that is. I'd be happy to set up an account on the box if anybody's willing to take a peak.

**Comment by tyrope** [comment]
@trezy Please post the latest entry in the exceptions.log, if available.

**Comment by Marenthyu** [comment]
Closing as all nessesary instructions are in the README.md
