### ISSUE TITLE
Private group instructions command

### ISSUE THREAD

**Issue by CptShinobi** [FuelRats/pipsqueak#38]
!pg <client name> = <Client name> Log out to main menu, click **Start**, then **Private Group**, then the rat's group.

**Comment by duk3luk3** [comment]
That is pc-specific, what would be the equivalent instruction for xbox?

**Comment by tyrope** [comment]
Last I checked, Xbox ED doesn't have private groups?

**Comment by tyrope** [comment]
@CptShinobi Could you reply to our questions regarding the XBOne version of E:D?

**Comment by tyrope** [comment]
```
[0450.10Z] <&Cpt_Shinobi> xb1 doesn't have private groups
```

**Comment by Marenthyu** [comment]
Will get closed by a969fce932f8d24976f10484738263367069b876
