### ISSUE TITLE
Make sopelsqueak ready for production use

### ISSUE THREAD

**Issue by duk3luk3** [FuelRats/pipsqueak#39]
I would like to retire my old jaraco.irc based version of mecha asap.

What is needed to bring the new version to feature parity?

**Comment by rwaltr** [comment]
I think the main kicker right now is the API integration and API backend.

**Comment by duk3luk3** [comment]
Well since mechasqueak doesn't have any API functionality at all, that is not needed.

**Comment by tyrope** [comment]
@duk3luk3 I don't think you realize how heavily sopelsqueak relies on the API. It won't load if there's no valid API configured, and if it gets the wrong result it will crash.

CC @trezy

**Comment by duk3luk3** [comment]
Well that should be fixed :-)

**Comment by tyrope** [comment]
@duk3luk3 No. That's the entire reason for mecha2.0

edit: But if you insist, 9d3789f3de5a9d85e3f514fa47e45e6568792836 was the last commit before the API was integrated. Enjoy re-doing 3 months of work using a local database instead of the API.

**Comment by DerryBear** [comment]
In fairness this is half the reason Pipsqueak became a thing. And a thing of beauty at that. I think it would be awful to let all the solid work that went into that go to waste. Was it not clear to see where Pipsqueak was going from the outset or something? Is it fair to rip Pip down like this after all the work _everyone_ has put into making it work and making the correct connections for it.

**Comment by trezy** [comment]
@duk3luk3 If you're just looking to decommission mecha's old server then I'm sure we can set her up on a new server. We've definitely got plenty of space available for it. :-)

I would like to see pip 2 in a production ready state but the biggest benefit of the rewrite is hooking in to the API.

However, I do agree with @duk3luk3 that mecha should be reasonably tolerant. If the API crashes or goes down for maintenance Mecha shouldn't crash. :-)

**Comment by duk3luk3** [comment]
Not letting work go to waste is the main reason I want to do this. I don't want to do any more code on the old mechasqueak because that would be a waste.

> However, I do agree with @duk3luk3 that mecha should be reasonably tolerant. If the API crashes or goes down for maintenance Mecha shouldn't crash. :-)

Exactly. Everything that is critical for live rescues should work with or without an API connection.

**Comment by tyrope** [comment]
Having a 'local fallback' makes sense, and I wouldn't be against that (heck, I encourage it). This however would require going through the codebase with a fine comb and re-doing /every/ call to the API to:
- Confirm we're not running in 'offline mode'
- If we're NOT in offline mode:
  - Test if the API is responsive.
  - If the API is responsive:
    - Act as we do now (Shadow copy to local db?)
  - if the API is not responsive:
    - Enable 'offline mode'
    - Switch to local db
- If we're in offline mode:
  - Use local db.
  - Test if the API is responsive.
  - If the API is responsive:
    - Update API with changes in the local db
    - Disable 'offline mode'
    - Switch to API

One may have noticed I've not been updating my branch lately, that's because of this reason. It just sounds like a lot of work to ensure something (that should be running on the same server anyway!) didn't break.

Patches Welcome.

**Comment by duk3luk3** [comment]
I'll be working on that today.

**Comment by trezy** [comment]
@tyrope You think Mecha and the API should be running on the same server in production? The API is intended to run on its own server since mecha isn't the only client it will be serving.

**Comment by rwaltr** [comment]
> @tyrope You think Mecha and the API should be running on the same server in production? The API is intended to run on its own server since mecha isn't the only client it will be serving.

Virtualization is your friend. You could vagrant or dockerize it. That way
if it goes down, doesn't take the server with it

**Comment by tyrope** [comment]
@trezy On one side, it would mean that the services are guaranteed to talk to each other (due to not needing external communication).
On the other side it puts everything on a single point of failure.

**Comment by rwaltr** [comment]
Remind me, is our server a VPS on the cloud?

On Sun, Jan 17, 2016 at 2:43 PM, Dimitri Molenaars <notifications@github.com

**Comment by trezy** [comment]
@Blackphidora It is indeed.

**Comment by Marenthyu** [comment]
Guess this is closed as RatSqueak IS running on a Sopel Version.
