### ISSUE TITLE
Add different Languages for Facts/Instructions

### ISSUE THREAD

**Issue by Marenthyu** [FuelRats/pipsqueak#40]
We got a "lot" of Russian Clients lately, so adding the Facts/Instructions in Russian to pull from them would be great.

Off the top of my head the following at least should be included:
- !ruo2 - Russian Emergency o2 Question and instruction to log out asap if true
- !ruprep - Russian Prep
- !rufr - Russian Friendslist add instruction
- !ruwing - Russian Wing Instruction
- !rubeacon - Russian Beacon Instruction

Helpful would be to also have a general "!askru" to ask if the client speaks russian to simply confirm that fact.

Other maybe helpful languages to add:
- German (I could do that since im native german)
- Had one in my mind but forgot it

**Comment by tyrope** [comment]
DerryBear asked something similar not too long ago, but instead with a -XY suffix.

This is easyfix, and would only require the facts.json file to be translated.

**Comment by rwaltr** [comment]
If Sopel allows for multiple fact json files, I would recommend placing the languages in different factsheets

**Comment by tyrope** [comment]
I'd have to do a small rewrite, but loading several json files shouldn't be hard. (They'd have to be in a folder together.)

**Comment by rwaltr** [comment]
If you work on that, ill start working on different language factsheets.
With whatever languages the game has native support for.
