### ISSUE TITLE
Allow ! commands in PM

### ISSUE THREAD

**Issue by Albuca** [FuelRats/pipsqueak#43]
Since a lot of CMDRs are so used to typing ! before their commands, would it be possible for the bot to parse the message and remove a leading exclamation mark (if present) before processing the text that was passed to it?

End result: " list " and " !list " would both result in the bot replying with the list of cases.

Cheers!

**Comment by duk3luk3** [comment]
Yes, it should work like that.

**Comment by Albuca** [comment]
It would also be nice of the bot was case-insensitive. Some clients/rats like to type in caps and the bot dose not catch it...

**Comment by tyrope** [comment]
The way the framework is written means it doesn't need (and as such, doesn't listen to) prefixed commands.

The only way to add it would be to put a 'command','!command' alias, which means it would also work as !!command in public messages. Is this something we want to do? (It'd be an ugly hack but work... technically)

Also, the bot should be case insensitive, which command doesn't work in uppercase?

**Comment by Albuca** [comment]
It definitely would be a hack solution... but I do remember seeing someone use " ;list " the other day, so there are other prefixes still out there. 

It's not so much uppercase its ignoring, but mixed case. I use IRC on my phone when doing rescues so I can better follow what's going on. It likes to capitalize the first letter of a sentence, which the bot dosent pick up on. E.g. " !List " or just " List " if PMing the bot.

**Comment by tyrope** [comment]
Could not reproduce, are you sure you're testing v2.0?

```
[1045.01Z] <~Tyrope> !List
[1045.02Z] <&RatTy> Tyrope: 1 active case(s): [0]test (+ 0 inactive).
[1045.05Z] <~Tyrope> !LIst
[1045.05Z] <&RatTy> Tyrope: 1 active case(s): [0]test (+ 0 inactive).
[1045.08Z] <~Tyrope> !LiSt
[1045.08Z] <&RatTy> Tyrope: 1 active case(s): [0]test (+ 0 inactive).
```

```
[1045.38Z] <Tyrope> !list
[1045.39Z] <RatTy> Tyrope: 1 active case(s): [0]test (+ 0 inactive).
[1045.43Z] <Tyrope> !LiSt
[1045.44Z] <RatTy> Tyrope: 1 active case(s): [0]test (+ 0 inactive).
[1045.46Z] <Tyrope> !LIST
[1045.46Z] <RatTy> Tyrope: 1 active case(s): [0]test (+ 0 inactive).
[1045.48Z] <Tyrope> !LIst
[1045.49Z] <RatTy> Tyrope: 1 active case(s): [0]test (+ 0 inactive).
```

**Comment by Albuca** [comment]
Whoops! Definitely wasn't testing on 2.0...
Glad to know that works in 2.0 though!

I guess the only question we have now is if we want to edit the commands to include ! both !! so that ! commands would be recognized in PM's.  IMO its more a 'nice to have' than a 'need to have'.

**Comment by tyrope** [comment]
.. I just realized I misunderstood the entire problem.

Pipsqueak ONLY accepts commands with prefix, PM or channel. To write a hack for this would be very CPU-inefficient (as we'd need to regex every line for every command, as opposed to having the framework deal with it once.)

**Comment by Albuca** [comment]
What I was hoping for, was the bot _would_ accept commands with a prefix.
I just figured people would want it to continue accepting commands without the prefix -- but if the code runs faster without having to regex every statement sent to it, even better!
