### ISSUE TITLE
Operations support in Mecha 2.0

### ISSUE THREAD

**Issue by kenneaal** [FuelRats/pipsqueak#47]
Add support for the new API support for Operations. This can help separate out long-term cases from the main rescue board, cleaning up IRC board a bit.

!list should show for instance:
Myclient [0] Myclient2 [1](Plus 1 inactive and 1 operation)
!list -i would pull the inactive, but leave the operations.
!list -o would pull the operation as well.
!operations or !ops lists currently active operations.
!opname <casenumber/name> <name> - Converts a normal case to an operation and sets the name for that operation. Moves it to the operations queue.

!list should probably exclude rescues marked as operations in its default list, and only enumerate them.

**Comment by tyrope** [comment]
I like this idea, but I have a few questions. As such, an example:
1, Operation Active
2, Operation Inactive
3, Rescue Active
4, Rescue Inactive

`!list` = 3
`!list -i` = 34
`!list -o` = 13
`!list -io` = 1234
`!ops` = 1
`!ops -i` = 12

`!opname 1 To the Edge and Back` => Operation Active now renamed to Operation To the Edge and Back

Correct?

**Comment by Marenthyu** [comment]
@kenneaal can you reiterate to me please what "operations" are? i have so far not heard of them - Feel free to reopen if appropriate.

**Comment by Marenthyu** [comment]
> xlexious[25k]> wt is an operation
> xlexious[25k]> there is certainly no API support for that
> xlexious[25k]> nor has the word operation ever been in the source code

**Comment by kenneaal** [comment]
Operations are epic rescues, such as Operation Neospike. It's a handy way to clear rescues that might be on the board for a significant time, without needing to actually mark them as inactive, which is a bit of misnomer.

**Comment by SuperManifolds** [comment]
the way @trezy decided to store epic rescues was merely as a boolean flag in the database, if they are supposed to be their own special entities with their own name that will require a pretty radical redesign,

so, what are we doing here?

**Comment by trezy** [comment]
Noooooooooooope. I think we're discussing two different things here.

## Epic Rescues

The `epic` flag was supposed to be a manual operation so mods could mark rescues as epic as they saw fit. It's more of a review process than a way to track rescues.

## Named rescues (operations?)

So, the only thing we _should_ need to do here is add a name to rescues. For long running rescues I can see the value in being able to do this since our strategy thus far has been to add a note for the rescue that says, "DON'T DELETE ME." Names could be a nice, simple solution to that.

**Comment by SuperManifolds** [comment]
If all I need to do on the API side of the implementation is add a field I can definitely do that. Any other special treatment of these types of rescues would need to wait after launch

**Comment by Marenthyu** [comment]
If thats the only thing needed to be done i can also easily add the functionality to the bot.
