### ISSUE TITLE
Debriefing SOP command

### ISSUE THREAD

**Issue by rubenbeumer** [FuelRats/pipsqueak#55]
I created a !kgbfoam-like image, that can help (new) rats debrief a client. My idea was to add a command to it, something like !db <rat>, but that could be changed. Almost all of the rats I showed it to liked it, so Cpt_Shinobi told me to post it here.

Link: http://goo.gl/VT6qyc

**Comment by tyrope** [comment]
This would be a fact, I assume? `debrief` & `db`. Or maybe just `debrief` as to not confuse it with the common abbreviation for database.

**Comment by rubenbeumer** [comment]
It would be a fact, yes. I agree with the !debrief instead of !db, that helps keep it clear.

**Comment by dewiniaid** [comment]
One of the dev builds has support for creating and editing facts on the fly, so this would be easy to add.

As would changing our !kgbfoam link to avoid the hotlinking problem that's breaking it for some users.

**Comment by dewiniaid** [comment]
`<Drillsqueak[BOT]> Dewin: Added debrief-en - Guide for debriefing clients: http://goo.gl/VT6qyc (by Dewin)`
