### ISSUE TITLE
Add an new rat command

### ISSUE THREAD

**Issue by Lapotor** [FuelRats/pipsqueak#58]
Hello i think it would be good when we have an new rat command what give the new rat the most important links.

Like:
1. http://goo.gl/UXt8Ic | 2. http://goo.gl/kZ21WC | 3. http://goo.gl/3S8p8I | 4. http://goo.gl/1J1F6b | 5. http://goo.gl/4Y7QNB | 6. http://goo.gl/mDF03t

**Comment by dewiniaid** [comment]
#49 should make this downright trivial in the new bot.

Also, http://bitly.com/howtorat-2 should be in there somewhere.
