### ISSUE TITLE
German translation of !commands

### ISSUE THREAD

**Issue by MsHail** [FuelRats/pipsqueak#66]
{
    "xbeacon": "Um das Wingsignal zu aktivieren halte X und drücke dann rechts auf dem D-Pad. Dann drücke einmal Q, wähle Signal, drücke Leertaste und ändere es von "Aus" zu "Geschwader",
    "pcwing": "Um eine Geschwadereinladung zu senden, gehe zum Kommunikationsmenü (\u0002Taste 2\u000f), \u0002drücke ESC\u000f um das Chat Eingabefeld zu schließen, und gehe dann zum zweiten Panel (\u0002Default key E\u000f). Dann wähle den CMDR aus dem du die Winganfrage senden willst, drücke die Leertaste und wähle \u0002Geschwadereinladung\u000f.",
    "pcbeacon": "Um das Wingsignal zu aktivieren, gehe zum rechten Menü (\u0002Taste 4\u000f), gehe zum Funktionsmenü (\u0002Taste Q\u000f), wähle \u0002Signal\u000f und setze es auf \u0002Geschwader\u000f",
    "xwing": "Um die Rats zu deinem Geschwader hinzuzufügen, halte X und drücke dann hoch auf dem D-Pad, drücke einmal RB, dann wähle den Namen der Rat, drücke Leertaste und wähle [Geschwadereinladung]",
    "pcfr": "Um eine Freundesanfrage zu senden, gehe zum Menü (\u0002Drücke ESC\u000f), klicke auf \u0002Freunde und Private Gruppen\u000f, und drücke dann \u0002Freund hinzufügen\u000f",
    "prep": "Bitte droppe vom Supercruise, komm zum stehen und deaktiviere alle Module AUSSER der LEBENSERHALTUNG",
    "xfr": "Um die Rats zu deiner Freundesliste hinzuzufügen drücke doppelt auf den XBox Button, dann drücke Links auf dem D-Pad. Jetzt drücke auf A und suche nach dem Namen der Rat.",
    "xquit": "Bitte logge dich SOFORT aus, indem du \u0002START\u000f drückst und \u0002Save and Exit to Main Menu\u000f!",
    "pcquit": "Please log out of the game immediately by pressing \u0002ESC\u000f and selecting \u0002Speichern und zum Hauptmenü\u000f auswählst!",
    "filtergalmap": "Um zu lernen wie man die Galaxiekarte filtert, klicke auf diesen Link: http://bit.ly/1GKXCWv",
    "kgbfoam": "Um zu lernen wie man die Galaxiekarte filtert, klicke auf diesen Link: http://bit.ly/1GKXCWv",
    "galnet": "Hier ist ein Link zum GalNet: https://community.elitedangerous.com/galnet",
    "sc": "Bitte reaktiviere deine Schubdüsen und deinen Frameshiftantrieb, wähle alle Ziele AB und gehe in den Supercruisemodus. Flieg für circa fünf Sekunden weg vom Stern des Systems, dann droppe zurück in den normalen Raum.",
    "ratchat": "HEY! #fuelrats ist nur für Rettungsoperationen, wenn du/ihr reden möchtest, tritt bitte #RatChat bei indem du '/join #RatChat' in den Chat schreibst.",
    "rc": "HEY! #fuelrats ist nur für Rettungsoperationen, wenn du/ihr reden möchtest, tritt bitte #RatChat bei indem du '/join #RatChat' in den Chat schreibst.",
    "pw": "Zeit für den Papierkram! http://bit.ly/1lBp53V"

}

// German translation of the current mechasqueak commands I did a month ago for Phidora_Eclase.
//Questions, Feedback and everything else please to Becci in #RatChat.

**Comment by dewiniaid** [comment]
Added to my local copy with some syntax fixed.
