### ISSUE TITLE
Purge case with !invalidate or similar

### ISSUE THREAD

**Issue by kenneaal** [FuelRats/pipsqueak#67]
It should be possible to close a case and immediately mark it as Going/deletable, for those instances where someone misfires a signal or our friendly neighborhood trolls.

**Comment by dewiniaid** [comment]
I nominate !purge or !delete, with a confirmation requirenent.

Do we have API support for this?

We should probably determine under which circumstances we're okay letting a
case be purged without admin intervention. We also may want to flag cases
for deletion with a reason that admins can read, or something similar.

A better fix might be to reduce the number of false signals and manage
trolls:
- Disallow signals from all sources except #Fuelrats.  It's rare that
  someone accidentally sends one in that channel, and all real rescues should
  be in #FR
- Disallow commands from users that are not in one of the bot's channels.
  The user wouldn't need to send the commands in that channel, merely be
  present.
- Record who opened and who last modified a case.  If a troll silently
  lurks in one of our channels and spams !inject we can use that info to ban
  them.

#3 is something we (well, the API) should be doing anyways, but to work
well it would require the bot to be authorized to perform limited actions
on behalf of another account.

**Comment by kenneaal** [comment]
Mitigating the number of false signals is always a good thing, but it would be mitigation, not elimination. Thus, there will still be a need for the ability to remove them completely. As far as I know, we still see who injects cases, which would be the only way someone could open a case without triggering a signal, so we've got that part covered. So with the perms locked down to commands only being accessible by someone in the channel, it should be all good.

The API will need a modification to introduce a "deleted" flag or similar. Tagging Alex for that bit.

[--- Commented from Asana.com
#commenter Kenneth Aalberg
---[aa]

**Comment by dewiniaid** [comment]
We don't currently track the author on !inject.

I previously had asked for an API change to make quotes an array of dicts
rather than of strings so we could store better metadata in it -- author
and timestamp being among the things I wanted to add.  I don't think it
should just be appended to the end of the string.

**Comment by tyrope** [comment]
We DO store the author on !inject (The injected message is (was?) suffixed with [INJECT by **IRC nick**]

**Comment by Marenthyu** [comment]
The api currently does not allow for rescue deletions. If @xlexi adds the capability, i would add a command for (Bot-)Admins only.

**Comment by Marenthyu** [comment]
> xlexious[25k> the API allows for rescue deletions now, but it should only ever manually be done by an admin
> Marenthyu> we could use the ability to invalidate rescues though as #67 describes.
> xlexious[25k]> I could enable soft delete
> xlexious[25k]> that basically makes it so instead of actually deleting the ORM just flips a deleted boolean in the table
> Marenthyu> yea, like that.
> xlexious[25k]> I'll look into it tomorrow
> Marenthyu> sure.
