### ISSUE TITLE
Add @command as quiet alias of !command

### ISSUE THREAD

**Issue by dewiniaid** [FuelRats/pipsqueak#68]
Old Mecha has a !silence comment that quiets the bot in channel.

Rather than a global silence, we can add @ to run a command with no (non-error) feedback on commands where it makes sense.

Alternatively, this can be a user preference if we ever add those.

**Comment by dewiniaid** [comment]
Not easily possible with the current Sopel code, but the new command parsing API I'm building should simplify this.

**Comment by Marenthyu** [comment]
Unsure if this is nessesary. Reopen if need arises.
