### ISSUE TITLE
Mecha auto correction

### ISSUE THREAD

**Issue by chrisshowie** [FuelRats/pipsqueak#75]
Currently gives out a shortened version of the system name (dropping of the start of the system name) which makes it a pain to copy and paste the corrected name. Please give out full corrected system name.

**Comment by dewiniaid** [comment]
Mecha doesn't necessarily know where in a sentence a system name begins,
hence it only outputting a partial system name.  (This was deemed a better
option to repeating the entire line of text after autocorrection.)

However, when quotes are added to a case, they are added after any
autocorrection has been applied.

**Comment by Marenthyu** [comment]
wontfix, invalid
