### ISSUE TITLE
Remove !search cooldown, replace with PM-only response.

### ISSUE THREAD

**Issue by tyrope** [FuelRats/pipsqueak#9]
```
[2245.50Z] <DerryBear[AWAY]> Allow systems to be searched multiple times but have 2.0 pm the rat instead of post in the main channel 
[2245.56Z] <~Tyrope> Yeah, no, I typo'd.
[2246.00Z] <~Tyrope> And PM is no problem.
[2246.04Z] <~Tyrope> No cooldown at all then?
[2246.37Z] <DerryBear[AWAY]> No cooldown timer , but prevent channel spam by having the bot pm the rat who searched for thr system 
```

'2.0' mentioned here is sopelsqueak

**Comment by duk3luk3** [comment]
I think it should be like this:
1. Cooldown should be per-channel.
2. If search is issued within cooldown period, PM result

**Comment by trezy** [comment]
I'm with @tyrope on this one. I don't think we need cooldowns for PMs and searches done in #RatChat are usually unnecessary. However it would be nice if !search implicitly sent PMs but we could do !search public or some such to allow explicitly posting the search results to #RatChat. Such a command should retain the cooldown, of course.

**Comment by tyrope** [comment]
The problem I see with using any parameters, is that they _could_ be valid search terms (I don't know all the system name-schemes by heart)

**Comment by trezy** [comment]
It could also be an extended command such as !searchpublic.

**Comment by duk3luk3** [comment]
> The problem I see with using any parameters, is that they could be valid search terms (I don't know all the system name-schemes by heart)

There are no system names that have ' -' in them so nope that's totally safe. :D

> However it would be nice if !search implicitly sent PMs but we could do !search public or some such to allow explicitly posting the search results to #RatChat.

I think generally we need a mechanism to direct mecha to post results of commands given in a different channel or in PM directly into #fuelrats, but it needs to be thought-out well to keep the risk of spam very low and also keep the mental load on dispatchers low.

**Comment by tyrope** [comment]
> There are no system names that have ' -' in them so nope that's totally safe. :D

[Alrai Sector AK-R a4-3](https://eddb.io/system/35485), to think of one real quick. Sure it doesn't have the space-dash sequence but it has both character separate and as such could be mistyped easily.

Regarding the other half of your comment, I feel that's a discussion for a different issue thread since that's quite the overhaul. (Boy are we doing a lot of those lately.)

**Comment by duk3luk3** [comment]
I am perfectly aware that there are system names with dashes in them.

If you want we can use a character that should never appear in system names as parameter prefix; what about windows-style "/"?

**Comment by trezy** [comment]
Eeeeeew Windows. I prefer the pipe ( | ) myself. Or maybe œ.

**Comment by tyrope** [comment]
I want to resolve this before releasing 1.0, any final thoughts? (I'm still in favour of always returning searches in PM and removing the cooldown, since they're threaded people can search at the same time)

**Comment by dewiniaid** [comment]
As a user, I'd prefer the results are public by default, with the PM fallback on a repeated search.  If a bunch of rats are trying to figure jumps to a case and are realizing the system name is wrong, they're all going to be interested in the result from the first one that searches.

**Comment by dewiniaid** [comment]
The current version of !search is now much faster than before and yields results that are much smaller than before (single line of systems with levenshtein distances, rather than match% since I don't know the exact formula used).  This means the cooldown/etc is likely less important now.

I would like to bring back some of more extended search data at some point (perhaps as a modifier to !search), but not certain if it's needed yet.
