### ISSUE TITLE
System search causes SQL query to be output to chat instead of result

### ISSUE THREAD

**Issue by SuperManifolds** [FuelRats/pipsqueak#93]
**<Harkon_fry[Dispatch]>** !search Col 258 Sector IJ-C a 15-3.  
**<DrillSqueak[BOT]>** [SQL: 'SELECT starsystem.id AS starsystem_id, starsystem.name_lower AS starsystem_name_lower, starsystem.name AS starsystem_name, starsystem.word_ct AS starsystem_word_ct, starsystem.x AS starsystem_x, starsystem.y AS starsystem_y, starsystem.z AS starsystem_z, starsystem.prefix_id AS starsystem_prefix_id, levenshtein_less_equal(starsystem.name_lower, %(levenshtein_less_equal_1)s, %(levenshtein_less_equal_2)s) AS distance \nFROM sta

**Comment by Marenthyu** [comment]
Oh!

**Comment by Marenthyu** [comment]
please install fuzzystrmatch in the ratbot database - forgot that, sorry!

**Comment by SuperManifolds** [comment]
You have root you're welcome to do that when you have time, it's not a big issue people can use !search on ratsqueak in the meantime

**Comment by Marenthyu** [comment]
fixed, postgresql server with version 9.4 is now running on port 5434 with fuzzystrmatch installed. the other versions have been uninstalled and killed.
