### ISSUE TITLE
Multilingual !assign

### ISSUE THREAD

**Issue by SimplyLinn** [FuelRats/pipsqueak#94]
The add person to friends-message when doing !assign would be nice if it could be multilingual like all the facts are.

**Comment by Marenthyu** [comment]
That would require a lot of refactoring, since !assign is not part of the rat-facts module, but rather assigned to a method in rat-board.

**Comment by SuperManifolds** [comment]
Since the command gives a direct command to the client it is kind of necessary.
Is it not possible to make a rat-fact for the "Please add (rats) to your friends..." and trigger it from the assign command? The message directly to the rats would not need to be multilingual

**Comment by Marenthyu** [comment]
We should be able to add a line to the translation facts and pull it from there to trigger on the !assign command if an optional parameter is given, which will be interpreted as a language if the rat-fact module is loaded. Will look into it either tomorrow or on wednesday afternoon.

**Comment by Marenthyu** [comment]
This is tricky, still. Would be a lot easier if #100 happens.

**Comment by Marenthyu** [comment]
This is NOT happening as per request by Orange_Sheets - only the !crinst information will be provided in the client's language.
