### ISSUE TITLE
Implement block for creating cases with client name "ratsignal".

### ISSUE THREAD

**Issue by kenneaal** [FuelRats/pipsqueak#97]
Do not allow pipsqueak to create cases with a client name of "Ratsignal". Yell (loudly) at dispatchers when they attempt to inject cases with that name.

**Comment by Marenthyu** [comment]
will do, but propably for the configured signal word instead of ratsignal hardcoded.

**Comment by kenneaal** [comment]
Sounds like a good idea. (SQUEAK, xlexious! ;) )
